In [1]:
import pandas as pd

In [2]:
chicago_data_url = "https://raw.githubusercontent.com/terranigmark/curso-analisis-exploratorio-datos-platzi/main/Traffic_Crashes1.csv"

In [4]:
chicago_df = pd.read_csv(chicago_data_url)
chicago_df["CRASH_DATE"] = chicago_df["CRASH_DATE"].apply(
    lambda x: pd.to_datetime(x, errors="coerce", utc=True)
)

In [5]:
chicago_df.head(5)

,Unnamed: 0,CRASH_RECORD_ID,RD_NO,CRASH_DATE_EST_I,CRASH_DATE,POSTED_SPEED_LIMIT,TRAFFIC_CONTROL_DEVICE,DEVICE_CONDITION,WEATHER_CONDITION,LIGHTING_CONDITION,...,INJURIES_REPORTED_NOT_EVIDENT,INJURIES_NO_INDICATION,INJURIES_UNKNOWN,CRASH_HOUR,CRASH_DAY_OF_WEEK,CRASH_MONTH,LATITUDE,LONGITUDE,LOCATION,date_real
0,290702,9e97e92753166de921a0e87199513aa841142c6fbb3a1e...,JA154528,NaN,2017-02-14 10:00:00+00:00,30,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,...,0.0,1.0,0.0,10,3,2,42.001676,-87.666364,POINT (-87.666364005301 42.001675862416),2017-02-14
1,405524,e5fe82ab7757d630a7f79927113bc63b5bede0cda74665...,JC391213,NaN,2019-08-13 19:12:00+00:00,35,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLEAR,DAYLIGHT,...,0.0,8.0,0.0,19,3,8,41.940041,-87.650923,POINT (-87.650923222567 41.940040917032),2019-08-13
2,261834,8c8ea6db9e1950765419429e2732ba5598fc6f87ac9e0c...,JC273287,NaN,2019-05-22 08:30:00+00:00,25,STOP SIGN/FLASHER,FUNCTIONING PROPERLY,RAIN,DAYLIGHT,...,0.0,2.0,0.0,8,4,5,41.955854,-87.710645,POINT (-87.710644534923 41.955853610383),2019-05-22
3,38519,02671b7d36a9d189d607778816fec23bbb2e5ac3cd3039...,JA307115,NaN,2017-06-14 16:50:00+00:00,0,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,...,0.0,2.0,0.0,16,4,6,41.863734,-87.676313,POINT (-87.676312689993 41.863734390899),2017-06-14
4,420197,ef1b1d450f65c6d16245dffdd3304d93b8be7d7bbf47f3...,JB247942,NaN,2018-05-03 08:35:00+00:00,30,NO CONTROLS,NO CONTROLS,RAIN,DAYLIGHT,...,0.0,2.0,0.0,8,5,5,41.851794,-87.695223,POINT (-87.695223114296 41.851794251516),2018-05-03

In [7]:
chicago_df.groupby(["LIGHTING_CONDITION", "REPORT_TYPE", "CRASH_HOUR"]).agg(
    {"BEAT_OF_OCCURRENCE": "sum"}
)

                                                          BEAT_OF_OCCURRENCE
LIGHTING_CONDITION REPORT_TYPE                CRASH_HOUR
DARKNESS           AMENDED                    20                      1614.0
                   NOT ON SCENE (DESK REPORT) 0                      64739.0
                                              1                      60086.0
                                              2                      36251.0
                                              3                      39172.0
...                                                                      ...
UNKNOWN            ON SCENE                   19                      4735.0
                                              20                      8113.0
                                              21                      6122.0
                                              22                      9699.0
                                              23                      3176.0

[291 rows x 1 columns]

In [8]:
# lograr algo parecido usando pivot table
pd.pivot_table(chicago_df, index=["LIGHTING_CONDITION", "REPORT_TYPE"])

                                                   BEAT_OF_OCCURRENCE  \
LIGHTING_CONDITION     REPORT_TYPE
DARKNESS               AMENDED                            1614.000000
                       NOT ON SCENE (DESK REPORT)         1183.079090
                       ON SCENE                           1166.488235
DARKNESS, LIGHTED ROAD AMENDED                             922.666667
                       NOT ON SCENE (DESK REPORT)         1298.297699
                       ON SCENE                           1223.077152
DAWN                   NOT ON SCENE (DESK REPORT)         1137.302789
                       ON SCENE                           1183.760181
DAYLIGHT               AMENDED                            1261.692308
                       NOT ON SCENE (DESK REPORT)         1263.180461
                       ON SCENE                           1228.757692
DUSK                   AMENDED                             321.500000
                       NOT ON SCENE (DESK REPORT)         1252.676892
                       ON SCENE                           1223.255319
UNKNOWN                NOT ON SCENE (DESK REPORT)         1410.566406
                       ON SCENE                           1258.668394

                                                   CRASH_DAY_OF_WEEK  \
LIGHTING_CONDITION     REPORT_TYPE
DARKNESS               AMENDED                              5.000000
                       NOT ON SCENE (DESK REPORT)           4.100758
                       ON SCENE                             4.200000
DARKNESS, LIGHTED ROAD AMENDED                              6.333333
                       NOT ON SCENE (DESK REPORT)           4.208612
                       ON SCENE                             4.061258
DAWN                   NOT ON SCENE (DESK REPORT)           4.047809
                       ON SCENE                             4.049774
DAYLIGHT               AMENDED                              4.307692
                       NOT ON SCENE (DESK REPORT)           4.127474
                       ON SCENE                             4.129142
DUSK                   AMENDED                              3.500000
                       NOT ON SCENE (DESK REPORT)           4.034765
                       ON SCENE                             4.179331
UNKNOWN                NOT ON SCENE (DESK REPORT)           4.127438
                       ON SCENE                             4.010363

                                                   CRASH_HOUR  CRASH_MONTH  \
LIGHTING_CONDITION     REPORT_TYPE
DARKNESS               AMENDED                      20.000000     6.000000
                       NOT ON SCENE (DESK REPORT)   15.395450     6.903575
                       ON SCENE                     13.735294     6.786275
DARKNESS, LIGHTED ROAD AMENDED                      22.000000     4.333333
                       NOT ON SCENE (DESK REPORT)   15.688938     6.579065
                       ON SCENE                     12.978808     6.926159
DAWN                   NOT ON SCENE (DESK REPORT)   11.816733     6.900398
                       ON SCENE                      9.266968     6.909502
DAYLIGHT               AMENDED                      11.923077     7.000000
                       NOT ON SCENE (DESK REPORT)   12.749100     6.566031
                       ON SCENE                     12.275000     6.650740
DUSK                   AMENDED                      20.000000     6.000000
                       NOT ON SCENE (DESK REPORT)   16.787321     7.406953
                       ON SCENE                     16.905775     6.908815
UNKNOWN                NOT ON SCENE (DESK REPORT)   12.798440     6.931079
                       ON SCENE                     10.393782     6.844560

                                                   INJURIES_FATAL  \
LIGHTING_CONDITION     REPORT_TYPE
DARKNESS               AMENDED                           0.000000
                       NOT ON SCENE (DESK REPORT)        0.000000
                       ON SCENE                          0.000000
DARKNESS, LIGHTED ROAD AMENDED                           0.333333
                       NOT ON SCENE (DESK REPORT)        0.000000
                       ON SCENE                          0.004667
DAWN                   NOT ON SCENE (DESK REPORT)        0.000000
                       ON SCENE                          0.000000
DAYLIGHT               AMENDED                           0.000000
                       NOT ON SCENE (DESK REPORT)        0.000000
                       ON SCENE                          0.001334
DUSK                   AMENDED                           0.000000
                       NOT ON SCENE (DESK REPORT)        0.000000
                       ON SCENE                          0.003049
UNKNOWN                NOT ON SCENE (DESK REPORT)        0.000000
                       ON SCENE                          0.000000

                                                   INJURIES_INCAPACITATING  \
LIGHTING_CONDITION     REPORT_TYPE
DARKNESS               AMENDED                                    0.000000
                       NOT ON SCENE (DESK REPORT)                 0.015168
                       ON SCENE                                   0.039293
DARKNESS, LIGHTED ROAD AMENDED                                    0.000000
                       NOT ON SCENE (DESK REPORT)                 0.006310
                       ON SCENE                                   0.045667
DAWN                   NOT ON SCENE (DESK REPORT)                 0.003984
                       ON SCENE                                   0.027273
DAYLIGHT               AMENDED                                    0.000000
                       NOT ON SCENE (DESK REPORT)                 0.001981
                       ON SCENE                                   0.035862
DUSK                   AMENDED                                    0.000000
                       NOT ON SCENE (DESK REPORT)                 0.004098
                       ON SCENE                                   0.033537
UNKNOWN                NOT ON SCENE (DESK REPORT)                 0.001304
                       ON SCENE                                   0.005236

                                                   INJURIES_NON_INCAPACITATING  \
LIGHTING_CONDITION     REPORT_TYPE
DARKNESS               AMENDED                                        0.000000
                       NOT ON SCENE (DESK REPORT)                     0.027086
                       ON SCENE                                       0.208251
DARKNESS, LIGHTED ROAD AMENDED                                        0.000000
                       NOT ON SCENE (DESK REPORT)                     0.030438
                       ON SCENE                                       0.224667
DAWN                   NOT ON SCENE (DESK REPORT)                     0.051793
                       ON SCENE                                       0.186364
DAYLIGHT               AMENDED                                        0.076923
                       NOT ON SCENE (DESK REPORT)                     0.021342
                       ON SCENE                                       0.196058
DUSK                   AMENDED                                        1.000000
                       NOT ON SCENE (DESK REPORT)                     0.030738
                       ON SCENE                                       0.170732
UNKNOWN                NOT ON SCENE (DESK REPORT)                     0.010430
                       ON SCENE                                       0.052356

                                                   INJURIES_NO_INDICATION  \
LIGHTING_CONDITION     REPORT_TYPE
DARKNESS               AMENDED                                   2.000000
                       NOT ON SCENE (DESK REPORT)                1.934995
                       ON SCENE                                  1.679764
DARKNESS, LIGHTED ROAD AMENDED                                   1.000000
                       NOT ON SCENE (DESK REPORT)                2.057906
                       ON SCENE                                  1.841000
DAWN                   NOT ON SCENE (DESK REPORT)                1.948207
                       ON SCENE                                  1.818182
DAYLIGHT               AMENDED                                   2.615385
                       NOT ON SCENE (DESK REPORT)                2.104818
                       ON SCENE                                  2.041790
DUSK                   AMENDED                                   3.500000
                       NOT ON SCENE (DESK REPORT)                2.170082
                       ON SCENE                                  2.121951
UNKNOWN                NOT ON SCENE (DESK REPORT)                1.514993
                       ON SCENE                                  1.178010

                                                   INJURIES_REPORTED_NOT_EVIDENT  \
LIGHTING_CONDITION     REPORT_TYPE
DARKNESS               AMENDED                                          0.000000
                       NOT ON SCENE (DESK REPORT)                       0.033586
                       ON SCENE                                         0.115914
DARKNESS, LIGHTED ROAD AMENDED                                          0.000000
                       NOT ON SCENE (DESK REPORT)                       0.033779
                       ON SCENE                                         0.093000
DAWN                   NOT ON SCENE (DESK REPORT)                       0.035857
                       ON SCENE                                         0.059091
DAYLIGHT               AMENDED                                          0.000000
                       NOT ON SCENE (DESK REPORT)                       0.028726
                       ON SCENE                                         0.098103
DUSK                   AMENDED                                          0.000000
                       NOT ON SCENE (DESK REPORT)                       0.026639
                       ON SCENE                                         0.085366
UNKNOWN                NOT ON SCENE (DESK REPORT)                       0.007823
                       ON SCENE                                         0.020942

                                                   INJURIES_TOTAL  \
LIGHTING_CONDITION     REPORT_TYPE
DARKNESS               AMENDED                           0.000000
                       NOT ON SCENE (DESK REPORT)        0.075840
                       ON SCENE                          0.363458
DARKNESS, LIGHTED ROAD AMENDED                           0.333333
                       NOT ON SCENE (DESK REPORT)        0.070527
                       ON SCENE                          0.368000
DAWN                   NOT ON SCENE (DESK REPORT)        0.091633
                       ON SCENE                          0.272727
DAYLIGHT               AMENDED                           0.076923
                       NOT ON SCENE (DESK REPORT)        0.052049
                       ON SCENE                          0.331357
DUSK                   AMENDED                           1.000000
                       NOT ON SCENE (DESK REPORT)        0.061475
                       ON SCENE                          0.292683
UNKNOWN                NOT ON SCENE (DESK REPORT)        0.019557
                       ON SCENE                          0.078534

                                                   INJURIES_UNKNOWN  LANE_CNT  \
LIGHTING_CONDITION     REPORT_TYPE
DARKNESS               AMENDED                                  0.0  2.000000
                       NOT ON SCENE (DESK REPORT)               0.0  2.548673
                       ON SCENE                                 0.0  2.316279
DARKNESS, LIGHTED ROAD AMENDED                                  0.0  2.666667
                       NOT ON SCENE (DESK REPORT)               0.0  2.502168
                       ON SCENE                                 0.0  2.532380
DAWN                   NOT ON SCENE (DESK REPORT)               0.0  2.539216
                       ON SCENE                                 0.0  2.511905
DAYLIGHT               AMENDED                                  0.0  2.333333
                       NOT ON SCENE (DESK REPORT)               0.0  2.598294
                       ON SCENE                                 0.0  2.622534
DUSK                   AMENDED                                  0.0  5.000000
                       NOT ON SCENE (DESK REPORT)               0.0  2.404348
                       ON SCENE                                 0.0  2.582677
UNKNOWN                NOT ON SCENE (DESK REPORT)               0.0  1.857971
                       ON SCENE                                 0.0  1.702703

                                                    LATITUDE  LONGITUDE  \
LIGHTING_CONDITION     REPORT_TYPE
DARKNESS               AMENDED                     41.954006 -87.835332
                       NOT ON SCENE (DESK REPORT)  41.846363 -87.670044
                       ON SCENE                    41.842181 -87.675566
DARKNESS, LIGHTED ROAD AMENDED                     41.803556 -87.638638
                       NOT ON SCENE (DESK REPORT)  41.865385 -87.677251
                       ON SCENE                    41.839543 -87.651047
DAWN                   NOT ON SCENE (DESK REPORT)  41.847444 -87.674032
                       ON SCENE                    41.659530 -87.273856
DAYLIGHT               AMENDED                     41.884794 -87.677438
                       NOT ON SCENE (DESK REPORT)  41.859707 -87.669711
                       ON SCENE                    41.856271 -87.680507
DUSK                   AMENDED                     41.785816 -87.597958
                       NOT ON SCENE (DESK REPORT)  41.852063 -87.678158
                       ON SCENE                    41.854784 -87.677436
UNKNOWN                NOT ON SCENE (DESK REPORT)  41.870687 -87.684011
                       ON SCENE                    41.859140 -87.677764

                                                   NUM_UNITS  \
LIGHTING_CONDITION     REPORT_TYPE
DARKNESS               AMENDED                      2.000000
                       NOT ON SCENE (DESK REPORT)   1.973998
                       ON SCENE                     2.074510
DARKNESS, LIGHTED ROAD AMENDED                      1.666667
                       NOT ON SCENE (DESK REPORT)   1.997030
                       ON SCENE                     2.096358
DAWN                   NOT ON SCENE (DESK REPORT)   1.972112
                       ON SCENE                     2.036199
DAYLIGHT               AMENDED                      2.153846
                       NOT ON SCENE (DESK REPORT)   2.004048
                       ON SCENE                     2.064053
DUSK                   AMENDED                      2.500000
                       NOT ON SCENE (DESK REPORT)   1.993865
                       ON SCENE                     2.094225
UNKNOWN                NOT ON SCENE (DESK REPORT)   1.985696
                       ON SCENE                     2.020725

                                                   POSTED_SPEED_LIMIT  \
LIGHTING_CONDITION     REPORT_TYPE
DARKNESS               AMENDED                              30.000000
                       NOT ON SCENE (DESK REPORT)           27.621885
                       ON SCENE                             28.290196
DARKNESS, LIGHTED ROAD AMENDED                              20.000000
                       NOT ON SCENE (DESK REPORT)           28.476986
                       ON SCENE                             29.262252
DAWN                   NOT ON SCENE (DESK REPORT)           28.466135
                       ON SCENE                             28.343891
DAYLIGHT               AMENDED                              29.615385
                       NOT ON SCENE (DESK REPORT)           27.996582
                       ON SCENE                             28.331361
DUSK                   AMENDED                              40.000000
                       NOT ON SCENE (DESK REPORT)           28.139059
                       ON SCENE                             28.860182
UNKNOWN                NOT ON SCENE (DESK REPORT)           26.762029
                       ON SCENE                             26.031088

                                                     STREET_NO     Unnamed: 0
LIGHTING_CONDITION     REPORT_TYPE
DARKNESS               AMENDED                     8324.000000  322381.000000
                       NOT ON SCENE (DESK REPORT)  3777.507042  230103.153846
                       ON SCENE                    3991.017647  214160.031373
DARKNESS, LIGHTED ROAD AMENDED                     3077.666667  315089.333333
                       NOT ON SCENE (DESK REPORT)  3505.801782  233109.353378
                       ON SCENE                    3663.904967  219285.096358
DAWN                   NOT ON SCENE (DESK REPORT)  3835.406375  230564.916335
                       ON SCENE                    3942.570136  206568.773756
DAYLIGHT               AMENDED                     3802.846154  204369.538462
                       NOT ON SCENE (DESK REPORT)  3498.125315  229400.869647
                       ON SCENE                    3703.470710  215604.418935
DUSK                   AMENDED                     6000.000000  238542.500000
                       NOT ON SCENE (DESK REPORT)  3787.703476  224259.257669
                       ON SCENE                    3773.267477  236552.328267
UNKNOWN                NOT ON SCENE (DESK REPORT)  3886.239272  227247.088427
                       ON SCENE                    3932.880829  199036.533679

### Creando un filtro

In [9]:
chicago_df.filter(["LIGHTING_CONDITION", "REPORT_TYPE"])

      LIGHTING_CONDITION                 REPORT_TYPE
0               DAYLIGHT  NOT ON SCENE (DESK REPORT)
1               DAYLIGHT                    ON SCENE
2               DAYLIGHT                    ON SCENE
3                UNKNOWN                    ON SCENE
4               DAYLIGHT  NOT ON SCENE (DESK REPORT)
...                  ...                         ...
27956           DAYLIGHT                    ON SCENE
27957           DAYLIGHT  NOT ON SCENE (DESK REPORT)
27958           DAYLIGHT                    ON SCENE
27959           DAYLIGHT  NOT ON SCENE (DESK REPORT)
27960            UNKNOWN  NOT ON SCENE (DESK REPORT)

[27961 rows x 2 columns]

### Creando un crosstab

In [10]:
# los valores son la incidencia de registros que comparten los valores de condición de luz - tasa de ocurrencia
pd.crosstab(chicago_df["LIGHTING_CONDITION"], chicago_df["BEAT_OF_OCCURRENCE"])

BEAT_OF_OCCURRENCE,111.0,112.0,113.0,114.0,121.0,122.0,123.0,124.0,131.0,132.0,...,2521.0,2522.0,2523.0,2524.0,2525.0,2531.0,2532.0,2533.0,2534.0,2535.0
LIGHTING_CONDITION,,,,,,,,,,,,,,,,,,,,,
DARKNESS,2,3,3,14,5,13,4,5,7,8,...,9,3,4,5,1,7,3,12,1,3
"DARKNESS, LIGHTED ROAD",32,20,16,62,22,52,30,33,39,42,...,32,18,23,22,14,20,25,31,22,27
DAWN,2,3,2,8,3,4,3,3,3,1,...,4,3,0,4,1,2,1,2,2,1
DAYLIGHT,102,71,59,174,118,213,146,108,138,109,...,97,65,68,55,39,40,49,119,75,52
DUSK,6,3,0,6,2,10,6,5,8,3,...,11,4,4,1,2,1,4,4,6,1
UNKNOWN,1,1,2,12,0,6,3,5,2,2,...,5,6,5,1,4,0,6,2,8,5